-- CREATE TABLE "users" (
--   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "telegram_id" bigint UNIQUE NOT NULL,
--   "username" varchar,
--   "first_name" varchar,
--   "last_name" varchar,
--   "email" varchar,
--   "password" varchar,
--   "google_id" varchar,
--   "avatar" varchar,
--   "created_at" timestamp,
--   "updated_at" timestamp
-- );

CREATE TABLE "wallets" (
  "user_id" bigint,
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar,
  "balance" bigint DEFAULT 0,
  "updated_at" timestamp
);

CREATE TABLE "transactions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wallet_id" bigint,
  "amount" bigint,
  "reason" varchar,
  "checkin_id" bigint,
  "external_id" varchar,
  "created_at" timestamp
);

CREATE TABLE "challenges" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "description" text,
  "frequency" varchar DEFAULT 'daily',
  "is_group_challenge" boolean DEFAULT false,
  "start_date" date,
  "end_date" date,
  "checkin_deadline" time,
  "price_per_miss" bigint,
  "price_early_leave" bigint,
  "coins_per_checkin" integer,
  "created_at" timestamp
);

CREATE TABLE "user_challenges" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "challenge_id" bigint,
  "agreed_to_terms_at" timestamp,
  "status" varchar DEFAULT 'active',
  "created_at" timestamp
);

CREATE TABLE "checkins" (
  "challenge_id" bigint,
  "user_id" bigint,
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "due_date" date,
  "status" varchar DEFAULT 'pending',
  "completed_at" timestamp,
  "proof_data" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "payment_methods" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "provider" varchar,
  "token" varchar NOT NULL,
  "card_mask" varchar,
  "is_default" boolean DEFAULT false,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE UNIQUE INDEX ON "wallets" ("user_id", "type");

COMMENT ON COLUMN "wallets"."type" IS 'money, coin';

COMMENT ON COLUMN "transactions"."amount" IS '+/- value';

COMMENT ON COLUMN "transactions"."external_id" IS 'For Payme/Click';

COMMENT ON COLUMN "payment_methods"."provider" IS 'click, payme, uzum';

COMMENT ON COLUMN "payment_methods"."token" IS 'The recurring payment token';

COMMENT ON COLUMN "payment_methods"."card_mask" IS 'e.g. 8600 **** **** 1234';

COMMENT ON COLUMN "payment_methods"."is_default" IS 'Charge this one for penalties';

ALTER TABLE "wallets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("wallet_id") REFERENCES "wallets" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("checkin_id") REFERENCES "checkins" ("id");

ALTER TABLE "user_challenges" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_challenges" ADD FOREIGN KEY ("challenge_id") REFERENCES "challenges" ("id");

ALTER TABLE "checkins" ADD FOREIGN KEY ("challenge_id") REFERENCES "challenges" ("id");

ALTER TABLE "checkins" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "payment_methods" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
